In [1]:
import sys
sys.path.append('../')
import pandas as pd

In [2]:
from app.database.queries import get_product_sales, get_last_n_days_sales
from app.utils.data_preprocessing import prepare_timeseries, impute_data
from app.models.anomaly_detection import detect_anomalies
from app.models.forecasting_models import generate_forecast

/Users/nikhilraj/Hanuman/full-stack-ai/agent-kairos/kairos_env/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [3]:
product_a_sales = get_product_sales('A')

In [4]:
product_a_sales

           date   value
0    2024-03-15  119.42
1    2024-03-16  134.71
2    2024-03-17  136.31
3    2024-03-18  127.51
4    2024-03-19  116.83
..          ...     ...
725  2026-03-10  158.48
726  2026-03-11  140.22
727  2026-03-12  145.34
728  2026-03-13  149.61
729  2026-03-14  173.90

[730 rows x 2 columns]

In [5]:
product_a_sales2 = prepare_timeseries(product_a_sales)
product_a_sales2

          date   value
0   2024-03-15  119.42
1   2024-03-16  134.71
2   2024-03-17  136.31
3   2024-03-18  127.51
4   2024-03-19  116.83
..         ...     ...
725 2026-03-10  158.48
726 2026-03-11  140.22
727 2026-03-12  145.34
728 2026-03-13  149.61
729 2026-03-14  173.90

[730 rows x 2 columns]

In [6]:
product_a_sales3 = impute_data(product_a_sales2)
product_a_sales3

          date   value
0   2024-03-15  119.42
1   2024-03-16  134.71
2   2024-03-17  136.31
3   2024-03-18  127.51
4   2024-03-19  116.83
..         ...     ...
725 2026-03-10  158.48
726 2026-03-11  140.22
727 2026-03-12  145.34
728 2026-03-13  149.61
729 2026-03-14  173.90

[730 rows x 2 columns]

In [7]:
anomaly_df = detect_anomalies(product_a_sales3)
anomaly_df

138.15961643835615 15.080161082988889
          date   value   z_score  anomaly
0   2024-03-15  119.42 -1.242667    False
1   2024-03-16  134.71 -0.228752    False
2   2024-03-17  136.31 -0.122652    False
3   2024-03-18  127.51 -0.706200    False
4   2024-03-19  116.83 -1.414416    False
..         ...     ...       ...      ...
725 2026-03-10  158.48  1.347491    False
726 2026-03-11  140.22  0.136629    False
727 2026-03-12  145.34  0.476148    False
728 2026-03-13  149.61  0.759301    False
729 2026-03-14  173.90  2.370027    False

[730 rows x 4 columns]

Empty DataFrame
Columns: [date, value, anomaly]
Index: []

In [8]:
forecast_df = generate_forecast(product_a_sales3, periods=30)
forecast_df

22:15:31 - cmdstanpy - INFO - Chain [1] start processing
22:15:33 - cmdstanpy - INFO - Chain [1] done processing

          date    forecast
0   2024-03-15  122.055550
1   2024-03-16  134.018688
2   2024-03-17  136.874741
3   2024-03-18  128.768721
4   2024-03-19  116.858194
..         ...         ...
755 2026-04-09  142.911453
756 2026-04-10  154.660569
757 2026-04-11  166.574484
758 2026-04-12  169.381314
759 2026-04-13  161.226070

[760 rows x 2 columns]

In [7]:
product_a_sales_90_days = get_last_n_days_sales('A', 90)

In [8]:
product_a_sales_90_days

          date   value
0   2026-03-14  173.90
1   2026-03-13  149.61
2   2026-03-12  145.34
3   2026-03-11  140.22
4   2026-03-10  158.48
..         ...     ...
85  2025-12-19  148.26
86  2025-12-18  137.42
87  2025-12-17  132.23
88  2025-12-16  137.68
89  2025-12-15  152.59

[90 rows x 2 columns]

In [5]:
from app.tools.data_tool import get_data
from app.tools.forecast_tool import forecast_product
from app.tools.anomaly_tool import detect_product_anomalies
from app.tools.visualization_tool import plot_sales_history, plot_forecast, plot_anomalies

In [6]:
df = get_data('A')
df

          date   value
0   2024-03-15  119.42
1   2024-03-16  134.71
2   2024-03-17  136.31
3   2024-03-18  127.51
4   2024-03-19  116.83
..         ...     ...
725 2026-03-10  158.48
726 2026-03-11  140.22
727 2026-03-12  145.34
728 2026-03-13  149.61
729 2026-03-14  173.90

[730 rows x 2 columns]

In [7]:
forecast_df = forecast_product(df, forecast_periods=30)
forecast_df

ValueError: Neither `start` nor `end` can be NaT