In [1]:
import sys
sys.path.append('../')
import pandas as pd

In [2]:
from app.tools.data_tool import get_data
from app.tools.forecast_tool import forecast_product
from app.tools.anomaly_tool import detect_product_anomalies
from app.tools.visualization_tool import plot_sales_history, plot_forecast, plot_anomalies

/Users/nikhilraj/Hanuman/full-stack-ai/agent-kairos/kairos_env/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df = get_data('A')
df

          date   value
0   2024-03-15  119.42
1   2024-03-16  134.71
2   2024-03-17  136.31
3   2024-03-18  127.51
4   2024-03-19  116.83
..         ...     ...
725 2026-03-10  158.48
726 2026-03-11  140.22
727 2026-03-12  145.34
728 2026-03-13  149.61
729 2026-03-14  173.90

[730 rows x 2 columns]

In [4]:
forecast_df = forecast_product('A', forecast_periods=30)
forecast_df

07:53:02 - cmdstanpy - INFO - Chain [1] start processing
07:53:02 - cmdstanpy - INFO - Chain [1] done processing

         date   value
0  2024-03-15  119.42
1  2024-03-16  134.71
2  2024-03-17  136.31
3  2024-03-18  127.51
4  2024-03-19  116.83

          date    forecast product        ingestion_timestamp
0   2024-03-15  122.055550       A 2026-03-28 07:53:02.334423
1   2024-03-16  134.018688       A 2026-03-28 07:53:02.334423
2   2024-03-17  136.874741       A 2026-03-28 07:53:02.334423
3   2024-03-18  128.768721       A 2026-03-28 07:53:02.334423
4   2024-03-19  116.858194       A 2026-03-28 07:53:02.334423
..         ...         ...     ...                        ...
755 2026-04-09  142.911453       A 2026-03-28 07:53:02.334423
756 2026-04-10  154.660569       A 2026-03-28 07:53:02.334423
757 2026-04-11  166.574484       A 2026-03-28 07:53:02.334423
758 2026-04-12  169.381314       A 2026-03-28 07:53:02.334423
759 2026-04-13  161.226070       A 2026-03-28 07:53:02.334423

[760 rows x 4 columns]

In [5]:
anomaly_df = detect_product_anomalies('A')
anomaly_df

138.15961643835615 15.080161082988889
          date   value   z_score  anomaly
0   2024-03-15  119.42 -1.242667    False
1   2024-03-16  134.71 -0.228752    False
2   2024-03-17  136.31 -0.122652    False
3   2024-03-18  127.51 -0.706200    False
4   2024-03-19  116.83 -1.414416    False
..         ...     ...       ...      ...
725 2026-03-10  158.48  1.347491    False
726 2026-03-11  140.22  0.136629    False
727 2026-03-12  145.34  0.476148    False
728 2026-03-13  149.61  0.759301    False
729 2026-03-14  173.90  2.370027    False

[730 rows x 4 columns]

Empty DataFrame
Columns: [date, value, anomaly]
Index: []

In [6]:
fig = plot_sales_history(df)
fig.show()

In [7]:
fig2 = plot_forecast(df, forecast_df)
fig2.show()